version: "latest"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "music_notes_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgdbdata:/var/lib.postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdbdata: null